// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeMmsjc2Ie86zAEzNYQgmOehUWj47yNEw',
    appId: '1:878545620225:web:2cf010c16df4c2f0051f00',
    messagingSenderId: '878545620225',
    projectId: 'snapshelf-1',
    authDomain: 'snapshelf-1.firebaseapp.com',
    storageBucket: 'snapshelf-1.firebasestorage.app',
    measurementId: 'G-42RT0MVN9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4MAzjOkCpvM3dkRvwlC18s2V8tBtrucI',
    appId: '1:878545620225:android:b8cb4cb5638df36b051f00',
    messagingSenderId: '878545620225',
    projectId: 'snapshelf-1',
    storageBucket: 'snapshelf-1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqugiIhzl8JdUW3GSf5BNDcBR7VE9KrMw',
    appId: '1:878545620225:ios:3dc929a477d69197051f00',
    messagingSenderId: '878545620225',
    projectId: 'snapshelf-1',
    storageBucket: 'snapshelf-1.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqugiIhzl8JdUW3GSf5BNDcBR7VE9KrMw',
    appId: '1:878545620225:ios:3dc929a477d69197051f00',
    messagingSenderId: '878545620225',
    projectId: 'snapshelf-1',
    storageBucket: 'snapshelf-1.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeMmsjc2Ie86zAEzNYQgmOehUWj47yNEw',
    appId: '1:878545620225:web:d40945922aebb3aa051f00',
    messagingSenderId: '878545620225',
    projectId: 'snapshelf-1',
    authDomain: 'snapshelf-1.firebaseapp.com',
    storageBucket: 'snapshelf-1.firebasestorage.app',
    measurementId: 'G-7N18PFDG6P',
  );
}
